config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :restaurants do
    resources :reviews, only: [ :new, :create ]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/change_phone_column.rb
class ChangePhoneColumn < ApplicationRecord
  def change
    rename_column :restaurants, :phone, :phone_number
    change_column :restaurants, :phone_number, :string
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :address, presence: true
  validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, presence: true
  validates :rating, inclusion: { in: (0..5) }
  validates :rating, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    @restaurants = Restaurant.all
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end

  def show
    @review = Review.new
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to restaurant_path(@restaurant)
    else
      render :edit
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

    def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: [:new, :create]

  def new
    @review = Review.new
  end

  def create
    # POST /restaurants/:restaurant_id/reviews
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant), notice: 'Review was successfully saved.'
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <div class="navbar-wagon"></div>

    <%= yield %>
    <div class="footer"></div>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @restaurant.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-info" %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<div class="container">
  <h1>Editing Restaurant</h1>
  <%= render 'form', restaurant: @restaurant %>
  <%= link_to 'Show', @restaurant %> |
  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h1 class="homepage">Restaurants</h1>

<table class="homepage">
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Phone Number</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.address %></td>
        <td><%= restaurant.phone_number %></td>
        <td><%= restaurant.category %></td>
        <td><%= link_to 'Show', restaurant, class: "btn btn-link" %></td>
        <td><%= link_to 'Edit', edit_restaurant_path(restaurant), class: "btn btn-link" %></td>
        <td><%= link_to 'Destroy', restaurant_path(restaurant), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-primary" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurant', new_restaurant_path, class: "btn btn-link" %>
</div>

app/views/restaurants/new.html.erb
<div class="container">
  <h1>New Restaurant</h1>

  <%= render 'form', restaurant: @restaurant %>

  <%= link_to 'Back', restaurants_path %>
</div>

app/views/restaurants/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h3>
  Name: <strong><%= @restaurant.name %></strong>
</h3>

<h3>
  Address: <strong><%= @restaurant.address %></strong>
</h3>

<h3>
  Contact: <strong><%= @restaurant.phone_number %></strong>
</h3>

<h3>
  Category: <strong><%= @restaurant.category %></strong>
</h3>

<hr>

<h3>Reviews!</h3>
<ul>
  <% @restaurant.reviews.each do |review| %>
    <li><%= review.content %> - Rating: <%= review.rating %></li>
  <% end %>
</ul>

<hr>

<%= link_to 'Edit', edit_restaurant_path(@restaurant), class: "btn btn-info" %>
<%= link_to 'Back', restaurants_path, class: "btn btn-info" %>

</div>

<div class="container">
  <h3>New review</h3>
  <%= simple_form_for [@restaurant, @review] do |f| %>
    <%= f.input :content %>
    <%= f.input :rating, collection: (0..5) %>
    <%= f.submit 'Submit your review!', class: 'btn btn-info' %>
  <% end %>
</div>

<hr>
<hr>

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= simple_form_for [@restaurant, @review] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit 'Submit your review!', class: 'btn btn-primary' %>
<% end %>